# Header
menu:
  主页: /
  所有文章: /archives
  随笔: /tags/随笔
  技术: /tags/技术

# SubNav
subnav:
  github: https://github.com/Cogito2012
  weibo: http://weibo.com/u/3187172412
  zhihu: http://www.zhihu.com/people/Cogito2012

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /assets/img/head.jpg
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: Cogito2012
#是否开启云标签
tagcloud: true
tag:
    DeepLearning: /tags
    CNN: /tags
    Computer Vision: /tags

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 武汉大学IIP

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:Cogito2012/Cogito2012.github.io.git
  branch: master